import {before,after} from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {schemaStatements} from '../cloud/schema.mjs';
import {createCloudHandler} from '../cloud/handler.mjs';
import {hashPassword} from '../cloud/security.mjs';
import {registrationContract} from './registration-contract.mjs';
let pg,server,other,base,otherBase,admin,security;
const db={async query(s,p=[]){return(await pg.query(s,p)).rows;},async transaction(statements){return pg.transaction(async tx=>{const results=[];for(const [s,p=[]]of statements)results.push((await tx.query(s,p)).rows);return results;});}};
const request=async(path,o={})=>{const r=await fetch(base+path,{method:o.method || 'GET',headers:{'Content-Type':'application/json','X-Requested-With':'LosCedros',...(o.cookie?{Cookie:o.cookie}:{}),...o.headers},...(o.body?{body:JSON.stringify(o.body)}:{})});return {status:r.status,data:(r.headers.get('content-type') || '').includes('application/json')?await r.json():await r.text(),headers:r.headers};};
before(async()=>{pg=new PGlite();for(const s of schemaStatements)await pg.exec(s);for(const [username,role]of [['admin','admin'],['seguridad','security']])await db.query('INSERT INTO users VALUES($1,$2,$3,$4)',[randomUUID(),username,hashPassword('Testing-Cloud!'),role]);for(const [key,value]of Object.entries({title:'LOS CEDROS NIGHT',subtitle:'El club',date:'',time:'',location:'Los Cedros',description:'Evento'}))await db.query('INSERT INTO settings VALUES($1,$2)',[key,value]);const id=randomUUID();await db.query('INSERT INTO inviters VALUES($1,$2,$3,$4,1,1,$5)',[id,'Juan Pérez','juan-perez','old-token',new Date().toISOString()]);await db.query('INSERT INTO guests(id,inviter_id,first_name,last_name,dni,search_name,photo_path,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[randomUUID(),id,'Registro','Anterior','30000000','registro anterior','dni/legacy.bin',new Date().toISOString()]);const options={db,secureCookies:false,pollInterval:30,streamDuration:3000};server=http.createServer(createCloudHandler(options));other=http.createServer(createCloudHandler(options));for(const s of [server,other])await new Promise(r=>s.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;otherBase='http://127.0.0.1:'+other.address().port;for(const username of ['admin','seguridad']){const r=await request('/api/login',{method:'POST',body:{username,password:'Testing-Cloud!'}});const cookie=r.headers.get('set-cookie').split(';')[0];if(username==='admin')admin=cookie;else security=cookie;}});
after(async()=>{for(const s of [server,other]){s.closeAllConnections();await new Promise(r=>s.close(r));}await pg.close();});
registrationContract('PostgreSQL',()=>({request,admin,security,otherBase,assertNoNewPhotos:async()=>assert.equal((await db.query("SELECT COUNT(*)::int AS n FROM guests WHERE photo_path<>''"))[0].n,1)}));
