import { test, expect } from '@playwright/test';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApplication } from '../../server.mjs';
let app, base, dir;
const password = 'Browser-Testing-2026!';
test.beforeAll(async () => {
  dir = mkdtempSync(join(tmpdir(),'cedros-ui-'));
  app = createApplication({ dataDir:dir,passwords:{ admin:password,seguridad:password } });
  await new Promise((r) => app.server.listen(0,'127.0.0.1',r));
  base = `http://127.0.0.1:${app.server.address().port}`;
});
test.afterAll(async () => { await app.close(); rmSync(dir,{ recursive:true,force:true }); });
const login = async (page, user) => { await page.goto(`${base}/login`); await page.getByLabel('Usuario',{ exact:true }).fill(user); await page.getByLabel('Contraseña',{ exact:true }).fill(password); await page.getByRole('button',{ name:'Iniciar sesión' }).click(); await expect(page.getByText('En tiempo real',{ exact:true })).toBeVisible(); };
const noOverflow = async (page) => expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
test('flyer, registro, administración y dos celulares sincronizados', async ({ browser }) => {
  const context = await browser.newContext({ viewport:{ width:1440,height:1000 } });
  const admin = await context.newPage(); const errors = [];
  admin.on('pageerror',(e) => errors.push(e.message));
  await admin.goto(base); await expect(admin.getByRole('heading',{ name:'Hay noches que son del club.' })).toBeVisible(); await noOverflow(admin);
  await admin.screenshot({ path:'test-results/landing-desktop.png',fullPage:true });
  await login(admin,'admin');
  const link = await admin.locator('#shared-link').inputValue();
  await admin.screenshot({ path:'test-results/admin-desktop.png',fullPage:true });
  const guestContext = await browser.newContext({ viewport:{ width:390,height:844 } });
  const guest = await guestContext.newPage(); guest.on('pageerror',(e) => errors.push(e.message));
  await guest.goto(link); await expect(guest.getByLabel('¿Quién te invita?')).toBeVisible(); await expect(guest.locator('input[type=file]')).toHaveCount(0); await noOverflow(guest);
  await guest.screenshot({ path:'test-results/invitation-mobile.png',fullPage:true });
  await guest.getByLabel('Nombre',{ exact:true }).fill('Lucía'); await guest.getByLabel('Apellido',{ exact:true }).fill('Gómez'); await guest.getByLabel('DNI',{ exact:true }).fill('40123456');
  await guest.getByLabel('¿Quién te invita?').fill('Juan Pérez');
  await guest.getByRole('checkbox').check(); await guest.getByRole('button',{ name:'Confirmar mi invitación' }).click();
  await expect(guest.getByText('YA ESTÁS EN LA LISTA',{ exact:true })).toBeVisible();
  await expect(admin.getByRole('button',{name:'Juan Pérez',exact:true})).toBeVisible();
  const phoneA = await browser.newContext({ viewport:{ width:390,height:844 } }); const phoneB = await browser.newContext({ viewport:{ width:360,height:800 } });
  const a = await phoneA.newPage(); const b = await phoneB.newPage();
  a.on('pageerror',(e) => errors.push(e.message)); b.on('pageerror',(e) => errors.push(e.message));
  await login(a,'seguridad'); await login(b,'seguridad');
  expect(await a.getByRole('searchbox').evaluate((el) => el.getBoundingClientRect().bottom)).toBeLessThan(550);
  await a.getByRole('searchbox').fill('gomez'); await b.getByRole('searchbox').fill('40123456');
  await expect(a.getByRole('button',{ name:'Lucía Gómez',exact:true })).toBeVisible();
  await expect(b.getByRole('button',{ name:'Lucía Gómez',exact:true })).toBeVisible(); await noOverflow(a); await noOverflow(b);
  await a.getByRole('button',{ name:'Ver DNI de Lucía Gómez' }).click();
  await expect(a.locator('.detail-dni')).toContainText('40123456');
  await expect(a.locator('.document-photo')).toHaveCount(0);
  await a.locator('#detail-enter').click();
  await expect(b.locator('.status-pill')).toHaveText('Ingresó');
  await expect(b.locator('.entry-time')).toBeVisible();
  await expect(a.locator('#detail-enter')).toBeDisabled();
  await a.getByRole('button',{ name:'Cerrar',exact:true }).click();
  await a.screenshot({ path:'test-results/security-mobile.png',fullPage:true });
  await admin.getByRole('button',{ name:'Invitados',exact:true }).click();
  await admin.getByRole('button',{ name:'Lucía Gómez',exact:true }).click();
  const guestId = await admin.locator('#guest-detail').getAttribute('data-id');
  await admin.request.post(`${base}/api/guests/${guestId}/revoke`,{ headers:{ 'X-Requested-With':'LosCedros' },data:{ revoked:true } });
  await expect(admin.getByRole('button',{ name:'Restaurar acceso individual',exact:true })).toBeVisible();
  await admin.getByRole('button',{ name:'Restaurar acceso individual',exact:true }).click();
  await expect(admin.getByRole('heading',{ name:'¿Restaurar este acceso?' })).toBeVisible();
  await admin.getByRole('button',{ name:'Confirmar',exact:true }).click();
  await expect(b.locator('.status-pill')).toHaveText('Ingresó');
  await admin.getByRole('button',{ name:'Evento y flyer' }).click();
  const downloadPromise = admin.waitForEvent('download'); await admin.getByRole('button',{ name:'Descargar flyer PNG' }).click();
  const download = await downloadPromise; expect(download.suggestedFilename()).toBe('los-cedros-night-flyer.png');
  await download.saveAs('test-results/flyer.png');
  await admin.getByLabel('Fecha',{ exact:true }).fill('2026-11-14'); await admin.getByLabel('Horario (Argentina)').fill('22:00');
  await admin.getByRole('button',{ name:'Guardar datos' }).click(); await expect(admin.getByText('14 de noviembre de 2026',{ exact:false }).first()).toBeVisible();
  expect(errors).toEqual([]);
  await context.close(); await guestContext.close(); await phoneA.close(); await phoneB.close();
});
